steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - uslocations_pipeline
  - --source=./functions/
  - --trigger-topic=dailyscheduled
  - --runtime=python39
  - --memory=1024MB
  - --timeout=540s
