steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - weather_pipeline
  - --source=./weather_pipeline
  - --trigger-topic=dailyscheduled
  - --runtime=python39
  - --memory=1024MB
  - --timeout=540s
