steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - websitehits_pipeline
  - --source=./functions
  - --trigger-topic=portfoliowebsite
  - --runtime=python39
  - --memory=1024MB
  - --timeout=540s
